config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'search#index'

  get '/search', to: 'search#search'

  get '/analytics', to: 'analytics#index', format: false

  get '/about', to: 'pages#about', format: false

  get '/help', to: 'pages#help', format: false
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @title = search_title
    @sorns = Sorn.none.page(params[:page]) # blank page on first visit
  end

  def search
    @fields_to_search = params[:fields] || Sorn::FIELDS # use either selected fields or all of them
    @sorns = filter_on_search
    @sorns = filter_on_agencies if params[:agencies]
    @sorns = filter_on_publication_date if publication_date_filter?
    @sorns = only_exact_matches if multiword_search?

    respond_to do |format|
      format.js { add_mentions_and_pagination }
      format.csv { create_csv_from_current_search }
    end
  end

  private

  def search_title
    if params[:search].present?
      "Search results for #{params[:search]} - "
    else
      ""
    end

  end

  def run_dynamic_search?
    params[:search].present?
  end

  def filter_on_search
    if !run_dynamic_search?
      Sorn.all
    elsif @fields_to_search == Sorn::FIELDS
      # If we are searching the whole SORN, just search the xml column
      Sorn.dynamic_search([:xml], params[:search])
    else
      # or search a list tsvectors columns
      Sorn.dynamic_search(@fields_to_search, params[:search])
    end
  end

  def filter_on_agencies
    filtered = @sorns.joins(:agencies).where(agencies: {name: params[:agencies]})
    # Matching on agencies could return duplicates, so get distinct
    if run_dynamic_search?
      filtered.get_distinct_with_dynamic_search_rank
    else
      filtered.get_distinct_no_dynamic_search_rank
    end
  end

  def publication_date_filter?
    params[:starting_year].present? || params[:ending_year].present?
  end

  def filter_on_publication_date
    if is_a_year? params[:starting_year]
      # from beginning of start year
      starting_date = params[:starting_year] + "-01-01"
      @sorns = @sorns.where('publication_date::DATE > ?', starting_date)
    end

    if is_a_year? params[:ending_year]
      # to end of ending year
      ending_date = params[:ending_year] + "-12-31"
      @sorns = @sorns.where('publication_date::DATE < ?', ending_date)
    end

    return @sorns
  end

  def multiword_search?
    params[:search].scan(/\w+/).size > 1 if params[:search].present?
  end

  def only_exact_matches
    # postgres is giving us matches where any search word is returned. We want only exact matches.
    ilikes_sql = @fields_to_search.map{ |field| "#{field} ILIKE :search"}.join(" OR ")
    @sorns = @sorns.where(ilikes_sql, search: "%#{params[:search]}%")
  end

  def is_a_year?(user_entered_date)
    # ignore user entered dates that aren't a year. Our html doesn't allow these submissions either.
    user_entered_date.present? && user_entered_date.match(/^\d{4}$/)
  end

  def add_mentions_and_pagination
    # only need to load mentioned and pagination for html
    @sorns = @sorns.includes(:mentioned)
    @sorns = @sorns.page(params[:page])
  end

  def create_csv_from_current_search
    send_data @sorns.to_csv(@fields_to_search.map(&:to_s)), filename: "sorns-#{Date.today.to_s}.csv"
  end
end

app/views/search/_agencies.html.erb
<div class="usa-accordion__heading">
  <button class="usa-accordion__button" aria-controls="agency-accordion" type="button">Agencies</button>
</div>
<div id="agency-accordion" class="usa-accordion__content usa-prose">
  <fieldset id="agencies" class="usa-fieldset">
    <button id='agency-deselect-all' class="clear-all usa-button usa-button--unstyled"><%= image_tag("close-red-50.svg", role: "img", alt: "")%>Clear agency filters</button>

    <label for="agency-search">Filter by agency name</label>
    <input id="agency-search" form="" class="agency-filter usa-input" type="text"></input>
    <div id="agency-filter-help-text" class="usa-prose" aria-live="polite" aria-atomic="true"></div>

    <div id="selected-agencies" class="list">
      <% Agency.all.each do |agency| %>
        <div class="usa-checkbox">
          <input class="usa-checkbox__input" id="agencies-<%= agency.name&.parameterize %>" type="checkbox" name="agencies[]" value="<%= agency.name %>" <%= "checked" if agency_selected?(agency.name) %> form="search-form">
          <label class="usa-checkbox__label agency-name" for="agencies-<%= agency.name&.parameterize %>"><%= agency.name %></label>
          <div class="agency-short-name" hidden><%= agency.short_name %></div>
        </div>
      <% end %>
    </div>
  </fieldset>
</div>

app/views/search/_page_count.html.erb
<%= page_entries_info @sorns, entry_name: '' %> <%= 'for "' + params[:search] +'"' if params[:search].present? %>

app/views/search/_page_menu.html.erb
<%= paginate @sorns, remote: true %>

app/views/search/_publication_date.html.erb
<div class="usa-accordion__heading">
  <button id="publication-year-button" class="usa-accordion__button" aria-controls="date-accoridon" type="button">Publication year</button>
</div>
<div id="date-accoridon" class="usa-accordion__content usa-prose  margin-top-0 margin-bottom-4">
  <fieldset id="publication-date-fields" class="usa-fieldset">
    <a id='dates-clear' class="clear-all"><%= image_tag("close-red-50.svg", role: "img", alt: "")%>Clear date filters</a>
    <div class="usa-form-group">
      <label class="usa-label margin-top-2" for="starting_year">Starting year</label>
      <span class="usa-hint" id="year-hint">For example: 1994</span>
      <input class="usa-input usa-input--inline" aria-describedby="year-hint" id="starting_year" name="starting_year" type="text" minlength="4" maxlength="4" pattern="[0-9]*" inputmode="numeric" value="<%= params[:starting_year] %>" form="search-form">
    </div>

    <div class="usa-form-group">
      <label class="usa-label" for="ending_year">Ending year</label>
      <span class="usa-hint">For example: <%= Date.today.year %></span>
      <input class="usa-input usa-input--inline" aria-describedby="year-hint" id="ending_year" name="ending_year" type="text" minlength="4" maxlength="4" pattern="[0-9]*" inputmode="numeric" value="<%= params[:ending_year] %>" form="search-form" >
    </div>
  </fieldset>
</div>

app/views/search/_sections.html.erb
<div id="sections">
  <div class="usa-accordion__heading">
    <button class="usa-accordion__button" aria-controls="section-accordion" type="button">Sections</button>
  </div>
  <div id="section-accordion" class="usa-accordion__content usa-prose">
    <fieldset id="sections" class="usa-fieldset">
      <button id='fields-deselect-all' class="clear-all usa-button  usa-button--unstyled"><%= image_tag("close-red-50.svg", role: "img", alt: "")%>Clear section filters</button>
      <div id="sorn-fields">
        <% Sorn::FIELDS.each do |field, index| %>
          <div class="usa-checkbox">
            <input class="usa-checkbox__input" id="fields-<%= field %>" type="checkbox" name="fields[]" value="<%= field %>" <%= "checked" if field_selected?(field.to_s) %> form="search-form">
            <label class="usa-checkbox__label" for="fields-<%= field %>"><%= field.to_s.humanize %></label>
          </div>
        <% end %>
      </div>
    </fieldset>
  </div>
</div>

app/views/search/index.html.erb
<% content_for :search do %>
  <%= javascript_include_tag "beforeSearch", type: "module" %>
<% end %>

<header id="search-header" class="margin-top-2 home-intro">
  <div class="grid-container site-intro">
    <div class="grid-row grid-gap grid-col-9">
      <h1 class="site-title">SORN Dashboard</h1>
      <p class="sub-title">This dashboard enables targeted search of System of Records Notices (SORN). The dashboard regularly pulls newly published SORNs from the Federal Register, and includes documents from 1994 to the present day. <%= link_to "Learn more about this tool", about_path %></p>
    </div>
  </div>
</header>

<section class="grid-container">
  <%= form_with local: false, url: search_path, method: "GET", id: "search-form", class: (params[:search].present? ? '' : 'pre-search') do %>
    <div class="desktop:grid-col-10 desktop:grid-offset-1 search-area">
      <label for="general-search">Search for SORNs by entering a keyword (will return exact matches)</label>
      <fieldset class="usa-search usa-search--big">
        <input class="usa-input" id="general-search" type="search" name="search" value="<%= params[:search] %>">
        <button id="general-search-button" class="usa-button" type="submit">
          <span class="usa-search__submit-text">Search</span>
        </button>
      </fieldset>
    </div>
  <% end %>
</section>

<section id="after-search">
  <div class="grid-container margin-top-2">
    <div class ="grid-row grid-gap">
      <div class="usa-layout-docs__sidenav desktop:grid-col-4">
        <div class="border border-base-dark sidebar">
          <div class="preview usa-prose site-prose" >
            <h2>Refine your search</h2>
            <div class="usa-accordion">
              <%= render partial: "sections" %>
              <%= render partial: "agencies" %>
              <%= render partial: "publication_date" %>
            </div>
          </div>
        </div>
        <div id="csv-download">
          <%= link_to search_path(:csv), id: "csv-link" do %>
            <%= image_tag("Download_Icon.svg", alt: "")%>
            <span class="csv-download-link-text">Download results as a CSV file</span>
          <% end %>
        </div>
      </div>

      <main class="usa-layout-docs__main usa-prose usa-layout-docs desktop:grid-col-8" id="main-content">
        <div id="active-filters" aria-live="polite" aria-relevant="additions removals">
          <div id="active-sections-filters">
            <div class="grid-row">
              <h2 class="labels">
                SECTION FILTERS
              </h2>
            </div>
            <div class="grid-row">
              <div id="active-fields">
              <% Sorn::FIELDS.each do |section| %>
                <div class="active-filter" id="fields-<%= section.to_s %>-badge">
                  <%= section.to_s.humanize %> <button class="remove-badge usa-button usa-button--unstyled"> <%= image_tag("uswds-2.9.0/close-blue-60v-alt.svg", role: "img", alt: "remove " + section.to_s.humanize + " filter")%></button>
                </div>
              <% end %>
              </div>
            </div>
          </div>

          <div id="active-agencies-filters">
            <div class="grid-row">
              <h2 class="labels">
                AGENCY FILTERS
              </h2>
            </div>
            <div class="grid-row">
              <div id="active-agencies">
                <% Agency.all.each do |agency| %>
                  <div class="active-filter" id="agencies-<%= agency.name&.parameterize %>-badge">
                    <%= agency.short_name || agency.name&.humanize %><button class="remove-badge usa-button usa-button--unstyled"><%= image_tag("uswds-2.9.0/close-blue-60v-alt.svg", role: "img", alt: "remove " + agency.name + " agency filter")%></button>
                  </div>
                <% end %>
              </div>
            </div>
          </div>

          <div id="active-date-filter">
            <div class="grid-row">
              <h2 class="labels">
                DATE RANGE
              </h2>
            </div>
            <div class="grid-row">
              <div id="active-dates">
                <div class="active-filter" id="active-date-range"><span></span><button class="remove-badge usa-button usa-button--unstyled"><%= image_tag("uswds-2.9.0/close-blue-60v-alt.svg", role: "img", alt: "remove date range filter")%></button></div>
              </div>
            </div>
          </div>
          <button class="usa-button apply-filters" type="submit"> Apply filters </button>
        </div>

        <div class="grid-row margin-bottom-1">
          <div class="grid-col-12">
            <div id="count" class="labels">
              <%= render 'page_count' %>
            </div>
          </div>
          <div class="grid-col-12 page-menu">
            <%= render 'page_menu' %>
          </div>
        </div>

        <ul id='cards' class="usa-card-group">
          <%= render @sorns %>
        </ul>

        <div class="grid-row">
          <div class="grid-col-12 page-menu">
            <%= paginate @sorns %>
          </div>
        </div>
      </main>

    </div>
  </div>
</section>

app/views/search/search.js.erb
// Any js that needs to run after a successful ajax request should go in here.

$("#count").html("<%= j(render partial: 'page_count', locals: {sorns: @sorns}) %>");
$(".page-menu").html("<%= j(render partial: 'page_menu', locals: {sorns: @sorns}) %>")
$("#cards").html("<%= j(render @sorns) %>");
// Build csv link from form params
$("#csv-link").attr("href", "search.csv?" + $("#search-form").serialize());

$("#after-search").show();
$("#search-form").removeClass("pre-search");
$("body").removeClass("pre-search");

// Add .agency-separator to agency pipe separator
$(".agency-names").html(function(_, html){
  return html.replace("|","<span class='agency-separator'>|</span>");
});

if ($("#general-search").val() == ""){
  $("#sections").hide();
} else {
  $("#sections").show();
}