config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'search#index'

  get '/search', to: 'search#search'

  get '/analytics', to: 'analytics#index', format: false

  get '/about', to: 'pages#about', format: false

  get '/help', to: 'pages#help', format: false
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= @title%>SORNS Dash</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uswds/2.9.0/css/uswds.min.css" integrity="sha512-1JfROzJI5km8+inC3KrHAsJ4Ufjl2nD7/TbCBXoMUeXi0LIAZntfLQr2S6ifV0lCuO0mWOOlNJNTgKzkj7b7wA==" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uswds/2.9.0/js/uswds.min.js" integrity="sha512-DK4Dfv782z/2seHu61hJL5WvFg95vZ64fKsqzeV7vTNcx01Ajp1kq5+w0QUNQ6GSakYyj6Mw0LZ/ddL5rNVMYQ==" crossorigin="anonymous"></script>

    <!-- We participate in the US government's analytics program. See the data at analytics.usa.gov. -->
    <script async type="text/javascript" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=GSA&subagency=TTS" id="_fed_an_ua_tag"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-QZ9W5STPKJ"></script>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag "application", type: "module" %>

    <%= content_for :search %>
 </head>

  <body <%if params[:search].blank? && current_page?('/') %>class="pre-search"<%end%>>
    <%= render template: 'layouts/banner' %>
    <%= render template: 'layouts/nav'%>
    <%= yield %>
    <%= render template: 'layouts/footer'%>
  </body>

</html>

app/views/layouts/banner.html.erb
<a class="usa-skipnav" href="#main-content">Skip to main content</a>
<section class="usa-banner" aria-label="Official government website">
  <div class="usa-accordion">
    <header class="usa-banner__header">
      <div class="usa-banner__inner">
        <div class="grid-col-auto">
          <img class="usa-banner__header-flag" src="<%= asset_path('uswds-2.9.0/us_flag_small.png') %>" alt="U.S. flag">
        </div>
        <div class="grid-col-fill tablet:grid-col-auto">
          <p class="usa-banner__header-text">An official website of the United States government</p>
          <p class="usa-banner__header-action" aria-hidden="true">Here’s how you know</p>
        </div>
        <button class="usa-accordion__button usa-banner__button"
          aria-expanded="false" aria-controls="gov-banner">
          <span class="usa-banner__button-text">Here’s how you know</span>
        </button>
      </div>
    </header>
    <div class="usa-banner__content usa-accordion__content" id="gov-banner">
      <div class="grid-row grid-gap-lg">
        <div class="usa-banner__guidance tablet:grid-col-6">
          <img class="usa-banner__icon usa-media-block__img" src="<%= asset_path('uswds-2.9.0/icon-dot-gov.svg') %>" role="img" alt="Dot gov">
          <div class="usa-media-block__body">
            <p>
              <strong>
                Official websites use .gov
</strong>
              <br/>
              A <strong>.gov</strong> website belongs to an official government organization in the United States.

            </p>
          </div>
        </div>
        <div class="usa-banner__guidance tablet:grid-col-6">
          <img class="usa-banner__icon usa-media-block__img" src="<%= asset_path('uswds-2.9.0/icon-https.svg') %>" role="img" alt="Https">
          <div class="usa-media-block__body">
            <p>
              <strong>
                Secure .gov websites use HTTPS
</strong>
              <br/>
              A <strong>lock</strong> (
<span class="icon-lock"><svg xmlns="http://www.w3.org/2000/svg" width="52" height="64" viewBox="0 0 52 64" class="usa-banner__lock-image" role="img" aria-labelledby="banner-lock-title banner-lock-description"><title id="banner-lock-title">Lock</title><desc id="banner-lock-description">A locked padlock</desc><path fill="#000000" fill-rule="evenodd" d="M26 0c10.493 0 19 8.507 19 19v9h3a4 4 0 0 1 4 4v28a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V32a4 4 0 0 1 4-4h3v-9C7 8.507 15.507 0 26 0zm0 8c-5.979 0-10.843 4.77-10.996 10.712L15 19v9h22v-9c0-6.075-4.925-11-11-11z"/></svg></span>
) or <strong>https://</strong> means you’ve safely connected to the .gov website. Share sensitive information only on official, secure websites.

            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/footer.html.erb
<section class="return-to-top">
  <div class="grid-container grid-container-desktop usa-footer__return-to-top">
    <div class="grid-row">
      <div class="grid-col-auto">
        <a href="#" class="return-to-top"><span>Return to top</span></a>
      </div>
    </div>
  </div>
</section>

<div class="usa-identifier">
  <section
    class="usa-identifier__section usa-identifier__section--masthead"
    aria-label="Agency identifier">
    <div class="usa-identifier__container"><div class="usa-identifier__logos">
        <a href="javascript:void(0);" class="usa-identifier__logo">
          <img
            class="usa-identifier__logo-img"
            
            src="<%= asset_path('gsa-logo-w100.png') %>"
            
            
            alt="&lt;GSA&gt; logo"
            
            role="img">
        </a></div><div class="usa-identifier__identity" aria-label="Agency description">
        <p class="usa-identifier__identity-domain">sorndashboard.fpc.gov</p>
        <p class="usa-identifier__identity-disclaimer">An official website of the <a href="https://www.gsa.gov/">General Services Administration</a></p>
      </div>
    </div>
  </section>
  <nav class="usa-identifier__section usa-identifier__section--required-links" aria-label="Important links">
    <div class="usa-identifier__container">
      <ul class="usa-identifier__required-links-list">
        <li class="usa-identifier__required-links-item">
          <a href="https://www.gsa.gov/about-us/organization/federal-acquisition-service/technology-transformation-services" class="usa-identifier__required-link">About the Technology Transformation Services</a>
        </li>
        <li class="usa-identifier__required-links-item">
          <a href="https://www.gsa.gov/website-information/accessibility-aids"
            class="usa-identifier__required-link">Accessibility support</a>
        </li>
        <li class="usa-identifier__required-links-item">
          <a href="https://www.gsa.gov/reference/freedom-of-information-act-foia"
            class="usa-identifier__required-link usa-link">FOIA requests</a>
        </li>
        <li class="usa-identifier__required-links-item">
          <a href="https://www.gsa.gov/about-us/organization/office-of-civil-rights/notification-and-federal-employee-antidiscrimination-and-retaliation-act-of-2002"
            class="usa-identifier__required-link usa-link">No FEAR Act data</a>
        </li>
        <li class="usa-identifier__required-links-item">
          <a href="https://www.gsaig.gov/" class="usa-identifier__required-link usa-link">Office of the Inspector General</a>
        </li>
        <li class="usa-identifier__required-links-item">
          <a href="https://www.gsa.gov/reference/reports/budget-performance" class="usa-identifier__required-link usa-link">Performance reports</a>
        </li>
      </ul>
    </div>
  </nav>
  <section class="usa-identifier__section usa-identifier__section--usagov" aria-label="U.S. government information and services">
    <div class="usa-identifier__container">
      <div class="usa-identifier__usagov-description">Looking for U.S. government information and services?</div>
      <a href="https://www.usa.gov/" class="usa-link">Visit USA.gov</a>
    </div>
  </section>
  </div>

app/views/layouts/nav.html.erb
<div class="usa-overlay"></div>
<header class="usa-header usa-header--basic">
  <div class="usa-nav-container">
    <div class="usa-navbar">
  <div class="usa-logo" id="basic-logo">
    <em class="usa-logo__text"><a href="/" title="Home"><%= image_tag("logo.svg", alt: "SORNS DASH - Home")%></a></em>
  </div>
  <button class="usa-menu-btn">Menu</button>
</div>
<nav aria-label="Primary navigation" class="usa-nav">
      <button class="usa-nav__close"><%= image_tag("uswds-2.9.0/close.svg", role: "img", alt: "close")%></button>
<ul class="usa-nav__primary usa-accordion">
    <li class="usa-nav__primary-item">
        <a class="usa-nav__link" href="/"><span>Home</span></a>
    </li>
    <li class="usa-nav__primary-item">
        <%= link_to 'About', about_path, class: "usa-nav__link" %>
    </li>

    <li class="usa-nav__primary-item">
        <%= link_to 'Help', help_path, class: "usa-nav__link" %>
    </li>
    </ul>
</nav>
  </div>
</header>